import utils

def generate_module_manifest_file(module_name: str) -> None:
    content = []
    content.append(f"# Module manifest file for module {module_name}\n# Auto-generated by DogeHeaderTool. Do not edit manually.\n\n")
    content.append(f"module_name: {module_name}\n")
    output_path = utils.get_module_manifest_file_path(module_name)
    utils.generate_file(output_path, "".join(content))