from pathlib import Path
import configs
import utils

def _append_module_configs_to_cmake_content(content: list[str], module_name: str) -> None:
    module_config: configs.DogeModuleConfig = configs.get_module_config(module_name)

    if module_config.reflect_headers:
        reflect_header_file_paths = [(module_config.module_dir / header).resolve().as_posix() for header in module_config.reflect_headers]
        content.append("# Reflect headers for this module\n")
        content.append("set(module_reflect_headers\n")
        for header_path in reflect_header_file_paths:
            content.append(f"    \"{header_path}\"\n")
        content.append(")\n\n")

    content.append("# Private dependencies for this module\n")
    content.append("set(module_private_dependencies\n")
    for dep in module_config.private_dependencies:
        content.append(f"    {dep}\n")
    content.append(")\n\n")

def _append_manifest_dependencies_to_cmake_content(content: list[str], module_name: str) -> None:
    manifest_dependent_file_paths = configs.collect_all_dependent_module_export_files(module_name)
    content.append("# Dependency files for generation of module manifest file\n")
    content.append("set(module_manifest_dependencies\n")
    for manifest_dep_file in manifest_dependent_file_paths:
        content.append(f"    \"{manifest_dep_file.as_posix()}\"\n")
    content.append(")\n\n")

def _append_module_paths_to_cmake_content(content: list[str], module_name: str) -> None:
    module_config = configs.get_module_config(module_name)
    content.append("# Paths related to this module\n")
    content.append(f"set(module_dir \"{module_config.module_dir.as_posix()}\")\n")
    content.append(f"set(module_config_file \"{module_config.config_file_path.as_posix()}\")\n")
    if module_config.has_export_file():
        content.append(f"set(module_dht_output_dir \"{utils.get_module_dht_output_dir(module_name).as_posix()}\")\n")
        content.append(f"set(module_export_file \"{utils.get_module_export_file_path(module_name).as_posix()}\")\n")
        content.append(f"set(module_manifest_file \"{utils.get_module_manifest_file_path(module_name).as_posix()}\")\n")
    content.append(f"set(module_definitions_header_dir \"{utils.get_module_definitions_header_path(module_name).parent.as_posix()}\")\n")
    content.append(f"set(module_definitions_header \"{utils.get_module_definitions_header_path(module_name).as_posix()}\")\n")
    content.append("\n")

def _make_module_cmake_file_content(module_name: str) -> str:
    module_config = configs.get_module_config(module_name)
    content = [f"# CMake file for module {module_name} of project {module_config.owning_project}\n# Auto-generated by DogeHeaderTool. Do not edit manually.\n\n"]
    _append_module_paths_to_cmake_content(content, module_name)
    _append_module_configs_to_cmake_content(content, module_name)
    if module_config.has_export_file():
        _append_manifest_dependencies_to_cmake_content(content, module_name)
    return "".join(content)

def generate_module_cmake_file(module_name: str) -> None:
    content = _make_module_cmake_file_content(module_name)
    output_path = utils.get_module_cmake_file_path(module_name)
    utils.generate_file(output_path, content)