from pathlib import Path
import configs
import utils

def _collect_module_manifest_dependencies(module_name: str) -> list[Path]:
    # module_cfg = config.get_module_config(module_name)
    # project_cfg = config.get_project_config(module_cfg.owning_project)
    
    # dependent_modules = config.collect_all_dependent_modules(module_name)

    return []

def _make_module_cmake_file_content(module_name: str) -> str:
    module_config = configs.get_module_config(module_name)
    
    manifest_dependent_file_paths = _collect_module_manifest_dependencies(module_name)
    reflect_header_file_paths = [(module_config.module_dir / header).resolve().as_posix() for header in module_config.reflect_headers]

    content = [f"# CMake file for module {module_name} of project {module_config.owning_project}\n"]
    content.append("# Auto-generated by DogeHeaderTool. Do not edit manually.\n\n")
    content.append("# Reflect headers for this module\n")
    content.append("set(module_reflect_headers\n{\n")
    for header_path in reflect_header_file_paths:
        content.append(f"    \"{header_path}\"\n")
    content.append(")\n\n")
    content.append("# Private dependencies for this module\n")
    content.append("set(module_private_dependencies\n{\n")
    for dep in module_config.private_dependencies:
        content.append(f"    {dep}\n")
    content.append(")\n\n")
    content.append("# Dependency files for generation of module manifest file\n")
    content.append("set(module_manifest_dependencies\n{\n")
    for dep_manifest_file in manifest_dependent_file_paths:
        content.append(f"    \"{dep_manifest_file.as_posix()}\"\n")
    content.append(")\n\n")
    
    return "".join(content)

def generate_module_cmake_file(module_name: str) -> None:
    content = _make_module_cmake_file_content(module_name)
    output_path = utils.get_module_cmake_file_path(module_name)
    utils.generate_file(output_path, content)