from pathlib import Path
import configs
import utils

def _append_project_paths_to_cmake_content(content: list[str], project_name: str) -> None:
    project_config = configs.get_project_config(project_name)
    content.append("# Paths related to this project\n")
    content.append(f"set(project_dir \"{project_config.project_dir.as_posix()}\")\n")
    content.append(f"set(project_config_file \"{project_config.config_file_path.as_posix()}\")\n")
    content.append(f"set(project_intermediate_build_dir \"{utils.get_project_intermediate_build_dir(project_name).as_posix()}\")\n")
    content.append("\n")

def _append_project_global_variables_to_cmake_content(content: list[str], project_name: str) -> None:
    project_config = configs.get_project_config(project_name)
    content.append("# Global variables for doge project\n")
    content.append(f"set(DOGE_PROJECT_DIR \"{project_config.project_dir.as_posix()}\")\n")
    content.append(f"set(DOGE_PROJECT_SOURCE_DIR \"{utils.get_project_source_dir(project_name).as_posix()}\")\n")
    content.append(f"set(DOGE_PROJECT_INTERMEDIATE_DIR \"{utils.get_project_intermediate_dir(project_name).as_posix()}\")\n")
    content.append(f"set(DOGE_PROJECT_BINARY_DIR \"{utils.get_project_binary_dir(project_name).as_posix()}\")\n")
    content.append(f"set(DOGE_PROJECT_CONFIG_DIR \"{utils.get_project_config_dir(project_name).as_posix()}\")\n")
    content.append("\n")

def _append_module_dirs_to_cmake_content(content: list[str], project_name: str) -> None:
    project_config = configs.get_project_config(project_name)
    content.append("# Module directories for this project\n")
    content.append(f"set(project_module_dirs\n")
    for module_name, module_dir in project_config.module_dirs.items():
        content.append(f"    \"{module_dir}\"\n")
    content.append(")\n\n")


def generate_project_cmake_file(project_name: str) -> None:
    content = [f"# CMake file for project {project_name}\n# Auto-generated by DogeHeaderTool. Do not edit manually.\n\n"]
    _append_project_paths_to_cmake_content(content, project_name)
    _append_project_global_variables_to_cmake_content(content, project_name)
    _append_module_dirs_to_cmake_content(content, project_name)
    output_path = utils.get_project_cmake_file_path(project_name)
    utils.generate_file(output_path, "".join(content))
