# Public, complete native-test declaration. Lower-level target/registration
# functions remain implementation primitives for specialized build fixtures.
include(GoogleTest)

function(durin_add_native_test target_name)
	set(_options SERIAL)
	set(_single KIND TIMEOUT PROCESSORS EXECUTION_HOST
		REQUIREMENT_RATIONALE HEAVY_RUNTIME_RATIONALE TARGET_LOCK_RATIONALE
		RUNTIME_ONLY_RATIONALE PRIVATE_SOURCE_OWNER PRIVATE_SOURCE_RATIONALE)
	set(_multi SOURCES PRIVATE_SOURCES LIBRARIES INCLUDE_DIRECTORIES
		COMPILE_DEFINITIONS DEPENDENCIES DATA_DIRECTORIES DATA_FILES
		REQUIRES ENVIRONMENTS RESOURCE_LOCKS LABELS
		RUNTIME_ONLY_TARGETS RUNTIME_ONLY_FILES DOMAINS MODULES BACKENDS STACKS)
	cmake_parse_arguments(PARSE_ARGV 1 TEST "${_options}" "${_single}" "${_multi}")
	if(TEST_UNPARSED_ARGUMENTS OR TEST_KEYWORDS_MISSING_VALUES)
		message(FATAL_ERROR "${target_name}: unknown arguments '${TEST_UNPARSED_ARGUMENTS}' or missing values '${TEST_KEYWORDS_MISSING_VALUES}'.")
	endif()
	if(NOT TEST_SOURCES OR NOT TEST_KIND OR NOT TEST_DOMAINS)
		message(FATAL_ERROR "${target_name} requires SOURCES, KIND and DOMAINS.")
	endif()
	set(_available TRUE)
	foreach(_requirement IN LISTS TEST_REQUIRES)
		if(_requirement STREQUAL "editor")
			if(NOT DURIN_WITH_EDITOR)
				set(_available FALSE)
			endif()
		else()
			message(FATAL_ERROR "${target_name}: unknown native-test requirement '${_requirement}'.")
		endif()
	endforeach()
	if(TEST_REQUIRES AND NOT TEST_REQUIREMENT_RATIONALE)
		message(FATAL_ERROR "${target_name}: REQUIRES needs REQUIREMENT_RATIONALE.")
	endif()
	foreach(_environment IN LISTS TEST_ENVIRONMENTS)
		if(NOT _environment STREQUAL "authored-shaders")
			message(FATAL_ERROR "${target_name}: unknown native-test environment '${_environment}'.")
		endif()
	endforeach()
	if(NOT _available)
		durin_exclude_native_test_sources(
			RATIONALE "${TEST_REQUIREMENT_RATIONALE}" SOURCES ${TEST_SOURCES})
		return()
	endif()

	add_durin_test(${target_name} ${TEST_SOURCES} ${TEST_PRIVATE_SOURCES})
	if(TEST_LIBRARIES)
		target_link_libraries(${target_name} PRIVATE ${TEST_LIBRARIES})
	endif()
	if(TEST_INCLUDE_DIRECTORIES)
		target_include_directories(${target_name} PRIVATE ${TEST_INCLUDE_DIRECTORIES})
	endif()
	if(TEST_COMPILE_DEFINITIONS)
		target_compile_definitions(${target_name} PRIVATE ${TEST_COMPILE_DEFINITIONS})
	endif()
	if(TEST_DEPENDENCIES)
		add_dependencies(${target_name} ${TEST_DEPENDENCIES})
	endif()
	foreach(_environment IN LISTS TEST_ENVIRONMENTS)
		# This environment has work only in authored/editor configurations.
		if(_environment STREQUAL "authored-shaders" AND DURIN_WITH_EDITOR)
			set(_source "${CMAKE_CURRENT_BINARY_DIR}/Generated/AuthoredShaderTestEnvironment-${target_name}.cpp")
			configure_file(
				"${CMAKE_CURRENT_FUNCTION_LIST_DIR}/../../Engine/Tests/NativeTestSupport/Private/AuthoredShaderTestEnvironment.cpp.in"
				"${_source}" COPYONLY)
			target_sources(${target_name} PRIVATE "${_source}")
			target_link_libraries(${target_name} PRIVATE DerivedDataCache ShaderBuild Slang_Imported)
		endif()
	endforeach()
	foreach(_property IN ITEMS HEAVY_RUNTIME_RATIONALE TARGET_LOCK_RATIONALE RESOURCE_LOCKS LABELS)
		if(TEST_${_property})
			set_property(TARGET ${target_name} PROPERTY DURIN_TEST_${_property} "${TEST_${_property}}")
		endif()
	endforeach()
	if(TEST_RUNTIME_ONLY_TARGETS OR TEST_RUNTIME_ONLY_FILES)
		durin_test_register_runtime_only_dependencies(${target_name}
			RATIONALE "${TEST_RUNTIME_ONLY_RATIONALE}"
			TARGETS ${TEST_RUNTIME_ONLY_TARGETS} FILES ${TEST_RUNTIME_ONLY_FILES})
	endif()
	foreach(_directory IN LISTS TEST_DATA_DIRECTORIES)
		durin_test_deploy_directory_to_data(${target_name} "${_directory}")
	endforeach()
	if(TEST_DATA_FILES)
		durin_test_deploy_files_to_data(${target_name} ${TEST_DATA_FILES})
	endif()
	set(_registration)
	foreach(_keyword IN ITEMS KIND TIMEOUT PROCESSORS EXECUTION_HOST
		PRIVATE_SOURCE_OWNER PRIVATE_SOURCE_RATIONALE DOMAINS MODULES BACKENDS STACKS)
		if(DEFINED TEST_${_keyword})
			list(APPEND _registration ${_keyword} "${TEST_${_keyword}}")
		endif()
	endforeach()
	if(TEST_SERIAL)
		list(APPEND _registration SERIAL)
	endif()
	durin_register_native_test(${target_name} ${_registration})
endfunction()
