# Platform-aware source classification for Durin modules.

include_guard(GLOBAL)

function(durin_platform_source_directory out_var target_platform)
	if("${target_platform}" STREQUAL "Win64")
		set(_durin_platform_directory "Windows")
	elseif("${target_platform}" STREQUAL "MacOS")
		set(_durin_platform_directory "MacOS")
	elseif("${target_platform}" STREQUAL "Linux")
		set(_durin_platform_directory "Linux")
	else()
		message(FATAL_ERROR
			"Unsupported DURIN_TARGET_PLATFORM '${target_platform}'. Expected Win64, MacOS, or Linux.")
	endif()
	set(${out_var} "${_durin_platform_directory}" PARENT_SCOPE)
endfunction()
function(durin_select_platform_sources out_sources out_foreign_headers target_platform)
	durin_platform_source_directory(_durin_selected_directory "${target_platform}")
	set(_durin_sources)
	set(_durin_foreign_headers)
	foreach(_durin_source IN LISTS ARGN)
		cmake_path(CONVERT "${_durin_source}" TO_CMAKE_PATH_LIST _durin_normalized)
		get_filename_component(_durin_extension "${_durin_normalized}" EXT)
		string(TOLOWER "${_durin_extension}" _durin_extension)
		set(_durin_is_header FALSE)
		if(_durin_extension MATCHES "^\\.(h|hpp|inl)$")
			set(_durin_is_header TRUE)
		endif()

		set(_durin_owned_directory "")
		foreach(_durin_platform_directory IN ITEMS Windows MacOS Linux)
			if(_durin_normalized MATCHES "/${_durin_platform_directory}/")
				set(_durin_owned_directory "${_durin_platform_directory}")
				break()
			endif()
		endforeach()

		if(NOT _durin_owned_directory OR _durin_owned_directory STREQUAL _durin_selected_directory)
			list(APPEND _durin_sources "${_durin_source}")
		elseif(_durin_is_header)
			# Foreign headers remain visible to IDEs but never participate in compilation.
			list(APPEND _durin_sources "${_durin_source}")
			list(APPEND _durin_foreign_headers "${_durin_source}")
		endif()
	endforeach()
	set(${out_sources} "${_durin_sources}" PARENT_SCOPE)
	set(${out_foreign_headers} "${_durin_foreign_headers}" PARENT_SCOPE)
endfunction()
