import sys
import os
import argparse

import helper
import symbols
import globals as g

def process_arguments():
    parser = argparse.ArgumentParser(description="A tool to process header files and generate code for Doge Engine.")
    parser.add_argument("-m", "--module", help="Specify the module to process.", required=True)
    parser.add_argument("-s", "--source", help="Specify the module source directory.", required=True)
    parser.add_argument("-o", "--output", help="Specify the output directory.", required=True)
    parser.add_argument("-i", "--input", help="Specify the file that contains the list of input header files.", default="")
    parser.add_argument("-d", "--deps", help="Specify the module dependencies, should be <dir>/<module_name>.json files separated by semicolons. These files can be generated by DogeHeaderTool.", default="")
    args = parser.parse_args()

    g.module_name = args.module
    g.module_source_dir = os.path.join("D:/Studyspace/Doge/Engine/Source/Runtime", g.module_name)

    with open(args.input, "r") as f:
        g.input_headers = [line.strip() for line in f.readlines() if line.strip()]
        
    g.module_dht_dir = helper.get_dht_dir(g.module_name)
    if args.deps:
        g.dependencies = [dep.strip() for dep in args.deps.split(";") if dep.strip()]

if __name__ == "__main__":
    process_arguments()

    os.makedirs(g.module_dht_dir, exist_ok=True)
    
    helper.init_logging()
    helper.init_clang()

    symbol_table = symbols.DHTModuleSymbolTable(
        g.module_name, helper.get_symbol_table_filepath(g.module_name)
    )
    symbol_table.load()
    symbol_table.update(g.input_headers, incremental=True)
    symbol_table.save()

