import os
import sys
import logging
import argparse

from config import *
import globals as g
import helper

def process_arguments():
    parser = argparse.ArgumentParser(description="A tool to process header files and generate code for Doge Engine.")
    parser.add_argument("--module", help="Specify the module to process.", required=True)
    parser.add_argument("--deps", help="Specify the module dependencies, should be <dir>/<module_name>.json files separated by semicolons. These files can be generated by DogeHeaderTool.", default="")
    args = parser.parse_args()

    g.module_name = args.module
    g.dht_dir = helper.get_dht_dir(g.module_name)
    if args.deps:
        g.dependencies = [dep.strip() for dep in args.deps.split(";") if dep.strip()]


def check_need_collect_module_info() -> bool:
    module_info_file = helper.get_dht_module_filepath(g.module_name)
    if not os.path.isfile(module_info_file):
        return True
    timestamp = os.path.getmtime(module_info_file)
    input_headers = helper.get_input_headers()
    # If any input header is newer than the module info file, we need to collect info
    for header in input_headers:
        if os.path.getmtime(header) > timestamp:
            return True
    return False

def collect_module_info():
    pass


def main():
    process_arguments()
    logging.basicConfig(level=logging_level, format='[%(levelname)s] %(message)s')
    
    logging.info(f"Processing module: {g.module_name}")
    logging.info(f"DHT Directory: {g.dht_dir}")
    logging.info(f"Dependencies: {g.dependencies}")

    os.makedirs(g.dht_dir, exist_ok=True) # Ensure DHT directory exists

    prerequisite_ok = True

    input_headers = helper.get_input_headers()
    for header in input_headers:
        logging.info(f" - {header}")
        if not os.path.isfile(header):
            logging.error(f"Input header file does not exist: {header}")
            prerequisite_ok = False

    if not prerequisite_ok:
        sys.exit(1)

if __name__ == "__main__":
    main()