from concurrent.futures import ThreadPoolExecutor, as_completed
from pathlib import Path
import configs
import utils

def _append_module_configs_to_cmake_content(content: list[str], module_name: str) -> None:
    module_config: configs.DurinModuleConfig = configs.get_module_config(module_name)

    if len(module_config.reflect_headers) > 0:
        reflect_header_file_paths = [(module_config.module_dir / header).resolve().as_posix() for header in module_config.reflect_headers]
        content.append("# Reflect headers for this module\n")
        content.append("set(module_reflect_headers\n")
        for header_path in reflect_header_file_paths:
            content.append(f"    \"{header_path}\"\n")
        content.append(")\n\n")

    if len(module_config.public_dependencies) > 0:
        content.append("# Public dependencies for this module\n")
        content.append("set(module_public_dependencies\n")
        for dep in module_config.public_dependencies:
            content.append(f"    {dep}\n")
        content.append(")\n\n")

    if len(module_config.private_dependencies) > 0:
        content.append("# Private dependencies for this module\n")
        content.append("set(module_private_dependencies\n")
        for dep in module_config.private_dependencies:
            content.append(f"    {dep}\n")
        content.append(")\n\n")

def _append_manifest_dependencies_to_cmake_content(content: list[str], module_name: str) -> None:
    manifest_dependent_file_paths = configs.collect_all_dependent_module_export_files(module_name)
    content.append("# Dependency files for generation of module manifest file\n")
    content.append("set(module_manifest_dependencies\n")
    for manifest_dep_file in manifest_dependent_file_paths:
        content.append(f"    \"{manifest_dep_file.as_posix()}\"\n")
    content.append(")\n\n")

def _append_module_paths_to_cmake_content(content: list[str], module_name: str) -> None:
    module_config = configs.get_module_config(module_name)
    content.append("# Paths related to this module\n")
    content.append(f"set(module_dir \"{module_config.module_dir.as_posix()}\")\n")
    content.append(f"set(module_config_file \"{module_config.config_file_path.as_posix()}\")\n")
    content.append(f"set(module_definitions_header_dir \"{utils.get_module_definitions_header_path(module_name).parent.as_posix()}\")\n")
    content.append(f"set(module_definitions_header \"{utils.get_module_definitions_header_path(module_name).as_posix()}\")\n")
    if module_config.has_export_file():
        content.append(f"set(module_dht_output_dir \"{utils.get_module_dht_output_dir(module_name).as_posix()}\")\n")
        content.append(f"set(module_export_file \"{utils.get_module_export_file_path(module_name).as_posix()}\")\n")
        content.append(f"set(module_manifest_file \"{utils.get_module_manifest_file_path(module_name).as_posix()}\")\n")
    content.append("\n")

_source_exts = ["*.cpp", "*.cc", "*.cxx", "*.h", "*.inl", "*.hpp"]

def _append_original_sources(content: list[str], module_name: str) -> None:
    module_config = configs.get_module_config(module_name)
    source_dir = module_config.module_dir

    def _scan(scan_dir: Path) -> list[Path]:
        if not scan_dir.exists():
            return []
        found_files = []
        for ext in _source_exts:
            found_files.extend([file.relative_to(source_dir) for file in scan_dir.rglob(ext)])
        return sorted(found_files)
    
    public_sources = _scan(source_dir / "Public")
    private_sources = _scan(source_dir / "Private")

    content.append("# Source files for this module\n")
    content.append(f"set(module_public_srcs\n")
    for src in public_sources:
        content.append(f"    \"{src.as_posix()}\"\n")
    content.append(")\n\n")

    content.append(f"set(module_private_srcs\n")
    for src in private_sources:
        content.append(f"    \"{src.as_posix()}\"\n")
    content.append(")\n\n")

def _append_generated_sources(content: list[str], module_name: str) -> None:
    module_config = configs.get_module_config(module_name)
    if len(module_config.reflect_headers) == 0:
        return
    
    module_dht_output_dir = utils.get_module_dht_output_dir(module_name)
    
    content.append("# Generated source files for this module\n")
    content.append("set(module_generated_srcs\n")
    for header in module_config.reflect_headers:
        filename_stem = Path(header).stem
        content.append(f"    \"{(module_dht_output_dir / f'{filename_stem}.gen.cpp').as_posix()}\"\n")
        content.append(f"    \"{(module_dht_output_dir / f'{filename_stem}.gen.h').as_posix()}\"\n")
    content.append(")\n\n")

def _make_module_cmake_file_content(module_name: str) -> str:
    module_config = configs.get_module_config(module_name)
    content = [f"# CMake file for module {module_name} of project {module_config.owning_project}\n# Auto-generated by DurinHeaderTool. Do not edit manually.\n\n"]
    content.append(f"set(module_name \"{module_name}\")\n")
    content.append(f"set(module_link_type \"{module_config.link_type.upper()}\")\n\n")
    if module_config.pch != "Self":
        content.append(f"set(module_pch_target \"{module_config.pch}\")\n\n")

    _append_module_paths_to_cmake_content(content, module_name)
    _append_module_configs_to_cmake_content(content, module_name)

    if module_config.has_export_file():
        _append_manifest_dependencies_to_cmake_content(content, module_name)

    _append_original_sources(content, module_name)
    _append_generated_sources(content, module_name)
    return "".join(content)


def generate_module_cmake_file(module_name: str) -> None:
    content = _make_module_cmake_file_content(module_name)
    output_path = utils.get_module_cmake_file_path(module_name)
    utils.generate_file(output_path, content)

# Generate the CMake files for all modules in a project parallely, to speed up the generation process. This is especially useful for projects with a large number of modules.
def generate_all_module_cmake_files_for_project(project_name: str) -> None:
    project_config = configs.get_project_config(project_name)
    # preload all module configs to avoid multiple loading of the same module config in different processes
    for module_name in project_config.modules.keys():
        configs.get_module_config(module_name)
        
    with ThreadPoolExecutor() as executor:
        futures_list = [executor.submit(generate_module_cmake_file, module_name) for module_name in project_config.modules.keys()]

        for future in as_completed(futures_list):
            future.result()