from pathlib import Path
import configs
import utils


def _append_project_paths_to_cmake_content(content: list[str], project_name: str) -> None:
    project_config = configs.get_project_config(project_name)
    content.append("# Paths related to this project\n")
    content.append(f"set(DURIN_PROJECT_CONFIG_FILE \"{project_config.config_file_path.as_posix()}\")\n")
    content.append(f"set(DURIN_PROJECT_INTERMEDIATE_BUILD_DIR \"{utils.get_project_intermediate_build_dir(project_name).as_posix()}\")\n")
    content.append("\n")

def _append_project_global_variables_to_cmake_content(content: list[str], project_name: str) -> None:
    project_config = configs.get_project_config(project_name)
    content.append("# Global variables for durin project\n")
    content.append(f"set(DURIN_PROJECT_DIR \"{project_config.project_dir.as_posix()}\")\n")
    content.append(f"set(DURIN_PROJECT_SOURCE_DIR \"{utils.get_project_source_dir(project_name).as_posix()}\")\n")
    content.append(f"set(DURIN_PROJECT_INTERMEDIATE_DIR \"{utils.get_project_intermediate_dir(project_name).as_posix()}\")\n")
    content.append(f"set(DURIN_PROJECT_BINARY_DIR \"{utils.get_project_binary_dir(project_name).as_posix()}\")\n")
    content.append(f"set(DURIN_PROJECT_CONFIG_DIR \"{utils.get_project_config_dir(project_name).as_posix()}\")\n")
    content.append(f"set(DURIN_PROJECT_CMAKE_DIR \"{utils.get_project_cmake_dir(project_name).as_posix()}\")\n")
    content.append("\n")


def _append_project_profile_to_cmake_content(content: list[str], project_name: str) -> None:
    profile_config = configs.get_profile_config(project_name, configs.PROFILE_NAME)
    content.append("# Active built-in profile for this project/build mode\n")
    if profile_config is None:
        raise ValueError(f"Unknown built-in profile '{configs.PROFILE_NAME}' for project {project_name}.")

    content.append(f"set(DURIN_PROJECT_PROFILE_NAME \"{profile_config.profile_name}\")\n")
    content.append(f"set(DURIN_PROJECT_PROFILE_WITH_EDITOR {'ON' if profile_config.with_editor else 'OFF'})\n")
    content.append(f"set(DURIN_PROJECT_PROFILE_APP_CONFIG_NAME \"{profile_config.app_config_name}\")\n")
    content.append("\n")


def _append_project_build_variables_to_cmake_content(content: list[str], project_name: str) -> None:
    profile_config = configs.get_profile_config(project_name, configs.PROFILE_NAME)
    if profile_config is None:
        raise ValueError(f"Unknown built-in profile '{configs.PROFILE_NAME}' for project {project_name}.")
    with_editor = 1 if profile_config.with_editor else 0
    with_developer_tools = 1 if configs.is_module_enabled_for_active_profile("MonaImGuiBackend") else 0

    content.append("# Derived build variables for this project/profile\n")
    content.append(f"set(DURIN_WITH_EDITOR {with_editor})\n")
    content.append(f"set(DURIN_WITH_DEVELOPER_TOOLS {with_developer_tools})\n")
    content.append("\n")
    content.append("set(DURIN_PROJECT_APP_CONFIG_NAME \"${DURIN_PROJECT_PROFILE_APP_CONFIG_NAME}\")\n")
    content.append("set(DURIN_PROJECT_BIN_ROOT \"${DURIN_PROJECT_BINARY_DIR}/${DURIN_ARCH}/$<CONFIG>\")\n")
    content.append("set(DURIN_PROJECT_RUNTIME_OUTPUT_DIR \"${DURIN_PROJECT_BIN_ROOT}/Runtime/${DURIN_PROJECT_PROFILE_NAME}\")\n")
    content.append("set(DURIN_PROJECT_THIRDPARTY_RUNTIME_DIR \"${DURIN_PROJECT_BIN_ROOT}/ThirdParty\")\n")
    content.append("set(DURIN_PROJECT_TEST_OUTPUT_DIR \"${DURIN_PROJECT_BIN_ROOT}/Tests\")\n")
    content.append("set(DURIN_PROJECT_LIB_OUTPUT_ROOT \"${DURIN_PROJECT_BIN_ROOT}/Lib\")\n")
    content.append("set(DURIN_PROJECT_SYMBOL_OUTPUT_ROOT \"${DURIN_PROJECT_BIN_ROOT}/Symbols\")\n")
    content.append("set(DURIN_PROJECT_EXTERNAL_RUNTIME_DIR \"${DURIN_PROJECT_THIRDPARTY_RUNTIME_DIR}\")\n")
    content.append("\n")

def _append_module_dirs_to_cmake_content(content: list[str], project_name: str) -> None:
    project_config = configs.get_project_config(project_name)
    enabled_module_names = configs.collect_enabled_modules_for_project(project_name, configs.PROFILE_NAME)
    enabled_module_dirs = [project_config.module_dirs[module_name] for module_name in project_config.module_dirs if module_name in enabled_module_names]

    content.append("# Module directories for this project\n")
    content.append("set(DURIN_PROJECT_MODULE_DIRS\n")
    for module_dir in enabled_module_dirs:
        content.append(f"    \"{module_dir}\"\n")
    content.append(")\n\n")


def generate_project_cmake_file(project_name: str) -> None:
    content = [f"# CMake file for project {project_name}\n# Auto-generated by DurinHeaderTool. Do not edit manually.\n\n"]
    _append_project_paths_to_cmake_content(content, project_name)
    _append_project_global_variables_to_cmake_content(content, project_name)
    _append_project_profile_to_cmake_content(content, project_name)
    _append_project_build_variables_to_cmake_content(content, project_name)
    _append_module_dirs_to_cmake_content(content, project_name)
    output_path = utils.get_project_cmake_file_path(project_name)
    utils.generate_file(output_path, "".join(content))
