#pragma once

enum EShaderStage : uint32
{
	SHADER_STAGE_VERTEX = 0U,
	SHADER_STAGE_PIXEL,
	SHADER_STAGE_GEOMETRY,
	SHADER_STAGE_MESH,
	SHADER_STAGE_AMPLIFICATION,
	NUM_NON_COMPUTE_SHADER_STAGES,
	SHADER_STAGE_COMPUTE = NUM_NON_COMPUTE_SHADER_STAGES,
	NUM_SHADER_STAGES,
};
