<?xml version="1.0" encoding="utf-8"?>
<Project ToolsVersion="4.0" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <ImportGroup Label="PropertySheets" />
  <PropertyGroup Label="UserMacros">
    <VulkanDir>%VULKAN_SDK%</VulkanDir>
    <DogeRoot>$([System.IO.Path]::GetFullPath('$(MSBuildThisFileDirectory)..\..\..'))</DogeRoot>
    <DogeWorkDir>$(DogeRoot)\Engine</DogeWorkDir>
    <DogeSourceDir>$(DogeWorkDir)\Source</DogeSourceDir>
    <DogeBinariesDir>$(DogeWorkDir)\Binaries</DogeBinariesDir>
    <DogeIntermediateDir>$(DogeWorkDir)\Intermediate</DogeIntermediateDir>
    <DogeThirdPartyDir>$(DogeSourceDir)\ThirdParty</DogeThirdPartyDir>
    <StdReferenceDir>$(DogeIntermediateDir)\Core\$(Platform)\$(Configuration)\microsoft\STL</StdReferenceDir>
    <GLFWBinariesDir>$(DogeThirdPartyDir)\glfw\build\src</GLFWBinariesDir>
    <DogePCHDir>$(DogeIntermediateDir)\$(ProjectName)\$(Platform)\$(Configuration)\PCHs</DogePCHDir>
    <DogeOutputName>DogeEditor-$(ProjectName)</DogeOutputName>
  </PropertyGroup>
  <PropertyGroup>
    <TargetExt>.dll</TargetExt>
    <CustomBuildBeforeTargets>
    </CustomBuildBeforeTargets>
    <OutDir>$(DogeBinariesDir)\$(ProjectName)\$(Platform)\$(Configuration)\</OutDir>
    <IntDir>$(DogeIntermediateDir)\$(ProjectName)\$(Platform)\$(Configuration)\</IntDir>
    <PublicIncludeDirectories>Public\</PublicIncludeDirectories>
    <PublicModuleDirectories>MPublic\</PublicModuleDirectories>
    <TargetName>$(DogeOutputName)</TargetName>
  </PropertyGroup>
  <ItemDefinitionGroup>
    <ClCompile>
      <AdditionalIncludeDirectories>$(ProjectDir)Private\;$(ProjectDir)Public\;$(DogeThirdPartyDir)\glm\;$(DogeThirdPartyDir)\spdlog\include\</AdditionalIncludeDirectories>
      <PrecompiledHeaderOutputFile>$(DogePCHDir)\PCH.$(ProjectName).pch</PrecompiledHeaderOutputFile>
      <PrecompiledHeaderFile>PCH.$(ProjectName).h</PrecompiledHeaderFile>
      <MultiProcessorCompilation>true</MultiProcessorCompilation>
      <EnableModules>true</EnableModules>
      <DebugInformationFormat>ProgramDatabase</DebugInformationFormat>
      <DisableSpecificWarnings>
      </DisableSpecificWarnings>
      <TreatSpecificWarningsAsErrors>
      </TreatSpecificWarningsAsErrors>
      <SDLCheck>true</SDLCheck>
      <WarningLevel>Level3</WarningLevel>
      <WarningVersion>17.10</WarningVersion>
      <AdditionalModuleDependencies>
      </AdditionalModuleDependencies>
      <LanguageStandard>stdcpplatest</LanguageStandard>
      <LanguageStandard_C>stdclatest</LanguageStandard_C>
      <PreprocessorDefinitions>_UNICODE;UNICODE;%(PreprocessorDefinitions)</PreprocessorDefinitions>
      <ForcedIncludeFiles>PCH.$(ProjectName).h</ForcedIncludeFiles>
      <AdditionalOptions>/utf-8 %(AdditionalOptions)</AdditionalOptions>
    </ClCompile>
    <PostBuildEvent>
      <Command>if EXIST "$(TargetDir)$(TargetName).dll" xcopy /Y "$(TargetDir)$(TargetName).dll" "$(DogeBinariesDir)\Doge\$(Platform)\$(Configuration)\"</Command>
    </PostBuildEvent>
    <CustomBuildStep>
      <Outputs>
      </Outputs>
      <Inputs>
      </Inputs>
    </CustomBuildStep>
    <Link>
      <AdditionalLibraryDirectories>$(DogeThirdPartyDir)\;%(AdditionalLibraryDirectories)</AdditionalLibraryDirectories>
      <AdditionalDependencies>%(AdditionalDependencies)</AdditionalDependencies>
    </Link>
  </ItemDefinitionGroup>
  <ItemGroup>
    <BuildMacro Include="VulkanDir">
      <Value>$(VulkanDir)</Value>
    </BuildMacro>
    <BuildMacro Include="DogeWorkDir">
      <Value>$(DogeWorkDir)</Value>
    </BuildMacro>
    <BuildMacro Include="DogeSourceDir">
      <Value>$(DogeSourceDir)</Value>
    </BuildMacro>
    <BuildMacro Include="DogeBinariesDir">
      <Value>$(DogeBinariesDir)</Value>
    </BuildMacro>
    <BuildMacro Include="DogeIntermediateDir">
      <Value>$(DogeIntermediateDir)</Value>
    </BuildMacro>
    <BuildMacro Include="DogeThirdPartyDir">
      <Value>$(DogeThirdPartyDir)</Value>
    </BuildMacro>
    <BuildMacro Include="StdReferenceDir">
      <Value>$(StdReferenceDir)</Value>
    </BuildMacro>
    <BuildMacro Include="GLFWBinariesDir">
      <Value>$(GLFWBinariesDir)</Value>
    </BuildMacro>
    <BuildMacro Include="DogePCHDir">
      <Value>$(DogePCHDir)</Value>
    </BuildMacro>
    <BuildMacro Include="DogeOutputName">
      <Value>$(DogeOutputName)</Value>
    </BuildMacro>
  </ItemGroup>
</Project>